openapi: 3.0.3
info:
  title: API de Gestión de Usuarios
  description: >
    Esta es una API de ejemplo para demostrar la estructura de OpenAPI (Swagger).
    Permite gestionar usuarios, incluyendo creación, lectura, actualización y eliminación.
  version: 1.0.0
  contact:
    name: Gabriel
    email: gabriel.hertzan@gmail.com

paths:
  /api/users:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"
        "500":
          description: Error al obtener los usuarios - Error en el servidor

  /api/users/{uid}:
    get:
      summary: Trae la info del usuario por el ID de Mongo
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: Id del usuario que se deseas traer
          schema:
            type: string
      responses:
        "200":
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor, La respuesta incluye información del error.

components:
  schemas:
    User:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
      properties:
        _id:
          type: string
          description: ID del usuario - autogenerado por MongoDB
          example: "651f2b3c4d5e6f7a8b9c0d1e"
        first_name:
          type: string
          description: Nombre del usuario
          example: "Gabriel"
        last_name:
          type: string
          description: Apellido del usuario
          example: "Hertzan"
        email:
          type: string
          format: email
          description: Email del usuario
          example: "gabriel.hertzan@gmail.com"
        password:
          type: string
          format: password
          description: Contraseña del usuario
          example: "123456"
        role:
          type: string
          description: Rol del usuario
          enum:
            - user
            - admin
          default: user
          example: "user"
        adopted_pets:
          type: array
          items:
            type: object
            properties:
              pet_id:
                type: string
                description: ID de la mascota referenciada
                example: "507f1f77bcf86cd799439011"

    UserDto:
      type: object
      properties:
        _id:
          type: string
          description: ID del usuario - autogenerado por MongoDB
          example: "3c0eb453ff45facaadce7039"
        name:
          type: string
          description: Nombre y apellido del usuario concatenado
          example: "Blick, Walter"
        role:
          type: string
          description: Rol del usuario
          enum:
            - user
            - admin
          example: "admin"
        email:
          type: string
          format: email
          description: Email del usuario
          example: "Conner.Kuhn@yahoo.com"
