openapi: 3.0.3
info:
  title: API de Adopciones
  description: API para la gestión de adopciones.
  version: 1.0.0

paths:
  /api/adoptions:
    get:
      summary: Obtiene todas las adopciones
      tags:
        - Adoptions
      responses:
        "200":
          description: Lista de adopciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Existing adoptions
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Adoption"
        "404":
          description: No se encontraron adopciones
        "500":
          description: Error interno del servidor
  /api/adoptions/{aid}:
    get:
      summary: Obtiene una adopción por su ID
      tags:
        - Adoptions
      parameters:
        - name: aid
          in: path
          required: true
          description: ID de la adopción
          schema:
            type: string
      responses:
        "200":
          description: Adopción encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Requested adoption
                  payload:
                    $ref: "#/components/schemas/Adoption"
        "404":
          description: Adopción no encontrada
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina una adopción
      tags:
        - Adoptions
      parameters:
        - name: aid
          in: path
          required: true
          description: ID de la adopción a eliminar
          schema:
            type: string
      responses:
        "200":
          description: Adopción eliminada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Deleted
                  payload:
                    $ref: "#/components/schemas/Adoption"
        "404":
          description: Adopción no encontrada
        "500":
          description: Error interno del servidor
  /api/adoptions/{pid}/user/{uid}:
    post:
      summary: Crea una nueva adopción
      tags:
        - Adoptions
      parameters:
        - name: pid
          in: path
          required: true
          description: ID de la mascota a adoptar
          schema:
            type: string
        - name: uid
          in: path
          required: true
          description: ID del usuario adoptante
          schema:
            type: string
      responses:
        "201":
          description: Adopción creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Adoption success
                  payload:
                    $ref: "#/components/schemas/Adoption"
        "400":
          description: Error de validación (Mascota ya adoptada, etc.)
        "404":
          description: Usuario o Mascota no encontrados
        "500":
          description: Error interno del servidor

components:
  schemas:
    Adoption:
      type: object
      properties:
        _id:
          type: string
          description: ID de la adopción
        pet_id:
          type: string
          description: ID de la mascota
        owner_user_id:
          type: string
          description: ID del usuario
      example:
        _id: 64a6f1b2c3d4e5f6a7b8c9d0
        pet_id: 64a6f1b2c3d4e5f6a7b8c9d1
        owner_user_id: 64a6f1b2c3d4e5f6a7b8c9d2
