openapi: 3.0.3
info:
  title: API de Gestión de Sesiones
  description: >
    Esta es una API de ejemplo para demostrar la estructura de OpenAPI (Swagger).
    Permite gestionar las sesiones, incluyendo creación, login, logout.
  version: 1.0.0
  contact:
    name: Gabriel
    email: gabriel.hertzan@gmail.com

paths:
  /api/session/register:
    post:
      summary: Registra un usuario
      description: Crea un nuevo usuario en el sistema a través del endpoint de sesión.
      tags:
        - Session
      requestBody:
        description: Datos del usuario a registrar
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
              properties:
                first_name:
                  type: string
                  example: "Gabriel"
                last_name:
                  type: string
                  example: "Hertzan"
                email:
                  type: string
                  format: email
                  example: "gabriel.hertzan@gmail.com"
                password:
                  type: string
                  format: password
                  example: "123456"
      responses:
        "201":
          description: Usuario creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User Created"
                  payload:
                    type: string
                    description: ID de MongoDB del usuario creado
                    example: "69716a68836bc8c15ac6ee7d"
        "400":
          description: Error en los datos enviados
        "500":
          description: Error al crear el usuario - Error en el servidor

  /api/session/login:
    post:
      summary: Login de usuario
      description: Inicia sesión validando credenciales y devuelve un token JWT en una cookie HttpOnly.
      tags:
        - Session
      requestBody:
        description: Credenciales del usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "gabriel.hertzan@gmail.com"
                password:
                  type: string
                  format: password
                  example: "123456"
      responses:
        "200":
          description: Login exitoso. La sesión se mantiene mediante cookies.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: authCookie=eyJhbGciOiJIUzI1Ni...; Path=/; HttpOnly
              description: Contiene el token JWT de autenticación.
        "500":
          description: Error en el servidor o credenciales inválidas (manejado por el try/catch)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Error"
                  message:
                    type: string
                    example: "Credential error"

  /api/session/logout:
    post:
      summary: Cerrar sesión
      description: Destruye la sesión del servidor y elimina las cookies 'connect.sid' y 'authCookie'.
      tags:
        - Session
      responses:
        "200":
          description: Sesión cerrada exitosamente
          headers:
            Set-Cookie:
              schema:
                type: string
                example: authCookie=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
              description: Instrucción para borrar la cookie en el navegador.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Logged out successfully"
        "500":
          description: Error al cerrar la sesión

  /api/session/current:
    get:
      summary: Obtener usuario actual
      description: Devuelve los datos del usuario logueado basándose en la cookie de sesión.
      tags:
        - Session
      responses:
        "200":
          description: Usuario autenticado encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  payload:
                    $ref: "../Users/Users.yaml#/components/schemas/UserDto"
        "401":
          description: No autorizado (Cookie inválida o expirada)
